// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvbnkrpwzejhbrctzjvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Ym5rcnB3emVqaGJyY3R6anZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDg5MDcsImV4cCI6MjA2Mzk4NDkwN30.GXsm1H7qUtAR3-pCU6JY64r7BJz6WDmryPs1pyIxkoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);